### ISSUE TITLE
GIL app not working

### ISSUE THREAD

**Issue by nhen917** [de-Boer-Lab/GIL#2]
![Capture](https://github.com/user-attachments/assets/b61e125d-9072-4064-94a0-a67d52de8150)

Hi there, I've been trying to run the GIL app, but every time I try to wake up the app from inactivity, I get an error message (attached). Thanks!

**Comment by OmartheOrganism** [comment]
Hi, 

This was caused by an environment error where the wrong version of numpy was being loaded after the app went down. The issue has now been corrected. 

Let us know if you have any other problems.
